{% set name = "spectrafit" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SpectraFit-{{ version }}.tar.gz
  sha256: 3345f06de575738953b2bf100843210bdd855dac9c02538fa9721e62cc5421fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - spectrafit = spectrafit.spectrafit:command_line_runner
    - spectrafit-converter = spectrafit.plugins.converter:command_line_runner

requirements:
  host:
    - pip
    - python >=3.6,<3.11
    - poetry >=1.1.13

  run:
    - emcee >=3.1.2,<4.0.0
    - lmfit >=1.0.3,<2.0.0
    - numdifftools >=0.9.39,<0.10.0
    - openpyxl >=3.0.9,<4.0.0
    - pandas >=1.3.0,<2.0.0
    - python >=3.6,<3.11
    - pyyaml >=6.0,<7.0
    - seaborn >=0.11.2,<0.12.0
    - tabulate >=0.8.10,<0.9.0
    - toml >=0.10.2,<0.11.0
    - tqdm >=4.64.0,<5.0.0

test:
  imports:
    - spectrafit
  commands:
    - spectrafit --help
    - spectrafit-converter --help

about:
  home: https://pypi.org/project/spectrafit/
  summary: Fast fitting of 2D-Spectra with established routines
  description: >-
    SpectraFit is a command-line tool for quick data-fitting
    based on the regular expression of distribution functions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://anselmoo.github.io/spectrafit/
  dev_url: https://github.com/anselmoo/spectrafit

extra:
  recipe-maintainers:
    - Anselmoo
